### ISSUE TITLE
Dockerfile todo list

### ISSUE THREAD

**Issue by certik** [Sumith1896/planet-sympy#3]
* [ ] Install all prerequisites and copy over the `planet` subdirectory in this repo and make sure it runs (see e.g. nbviewer's [Dockerfile](https://github.com/jupyter/nbviewer/blob/38efb5cd3e1ab5a5aa392d7dec06aabf33653991/Dockerfile) how to do that)
* [ ] Install cron to run the update periodically (see e.g. [here](https://www.ekito.fr/people/run-a-cron-job-with-docker/) for instructions)
* [ ] Add automatic push of the generated html pages into github from the cron job. This requires to have a github token, that will be passed to the docker image via an environment variable. On Travis we pass in a token for a test repository that we just keep somewhere. In production (e.g. on Linode), we put in a token for the planet.sympy.org github repo.

**Comment by Sumith1896** [comment]
Thanks for the TODO. Yes, this is a great of going about things.
